// <auto-generated />
using FinSignal.Midlayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinSignal.Midlayer.Migrations
{
    [DbContext(typeof(FinSignalDbContext))]
    partial class FinSignalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinSignal.Midlayer.Signals.InvoiceStatus", b =>
                {
                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("InvoiceAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("InvoiceNumber");

                    b.ToTable("InvoiceStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
